from datetime import date
from typing import Protocol

from packages.domain.models import (
    Bar,
    Trade,
    StrategyDefinition,
    Hypothesis,
    BacktestResult,
)


class MarketDataRepository(Protocol):
    async def get_bars(self, symbol: str, start: date, end: date) -> list[Bar]: ...
    async def save_bars(self, symbol: str, bars: list[Bar]) -> int: ...
    async def get_available_symbols(self) -> list[str]: ...


class StrategyRepository(Protocol):
    async def save(self, strategy: StrategyDefinition) -> StrategyDefinition: ...
    async def get(self, strategy_id: str) -> StrategyDefinition | None: ...
    async def list(self, status: str | None = None) -> list[StrategyDefinition]: ...


class HypothesisRepository(Protocol):
    async def save(self, hypothesis: Hypothesis) -> Hypothesis: ...
    async def get(self, hypothesis_id: str) -> Hypothesis | None: ...
    async def list(self, status: str | None = None) -> list[Hypothesis]: ...


class BacktestRepository(Protocol):
    async def save_result(self, result: BacktestResult) -> str: ...
    async def get_result(self, run_id: str) -> BacktestResult | None: ...
    async def list_results(self, strategy_id: str) -> list[BacktestResult]: ...


class TradeRepository(Protocol):
    async def save(self, trade: Trade) -> Trade: ...
    async def get_by_strategy(self, strategy_id: str) -> list[Trade]: ...
